spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/auth
    username: root
    password: cmpe172

jwt:
  issuer: HaircutAuthServer
  window: 3600
  key: dI77U8bhgMefJrG6qQpugl95n8bADM3shHbVO43vX+g=

server:
  error:
    include-message: always
  port: 8099

# Also need to disable auth on these endpoints to use them
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    # need the html to use this
    enabled: false